project:
  type: website
  output-dir: docs

website:
  title: "Análise Multivariada 2023"
  navbar:
    left:
      - href: index.qmd
        text: Página Principal
  sidebar:
    style: "docked"
    search: true
    contents:
      - part_1_prep.qmd
      - part_2_prep.qmd
  page-navigation: true

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

