---
title: "R Notebook"
author: "Seu Nome"
output: html_notebook
---

```{r setup}
library(here)
library(tidyverse)
library(FactoMineR)
library(factoextra)
```


## Questão 1

### 1.1 

```{r}
path_happy <- here::here("data_raw", "world-happiness-report-2021.csv")
HAPPY <- read.csv(path_happy, check.names = FALSE)
```

verificando os dados importados:

```{r}
dplyr::glimpse(HAPPY)
```


### 1.2 

```{r}
happy <- HAPPY[ ,8:12]
names(happy)
```


### 1.3 

```{r}
rownames(happy) <- HAPPY[ ,1]
```

verificando os dados:

```{r}
head(happy)
```



## Questão 2

### 2.1 

```{r}
happy_pca <- FactoMineR::PCA(happy, ncp = 5, graph = FALSE)
```

### 2.2 

```{r}
summary(happy_pca)
```


### 2.3

```{r}
factoextra::fviz_screeplot(
  happy_pca,
  choice = "variance",
  addlabels = TRUE,
  ylim = c(0, 100)
)
```


## Questão 3

### 3.1 

```{r}
factoextra::fviz_pca_var(happy_pca, col.var = "red", repel = TRUE)
```



## Questão 4

### 4.1 

```{r}
factoextra::fviz_pca_ind(happy_pca,
                         col.ind = "cos2",
                         repel = TRUE,
                         label = "ind") 
```


### 4.2 



## Questão 5

### 5.1 

```{r}
factoextra::fviz_pca_biplot(
  happy_pca,
  label = "var",
  col.var = "red",
  col.ind = "blue",
  repel = TRUE
)
```



## Questão 6




