---
title: "Análise Multivariada - Exame Final"
author: "Seu nome"
output: html_notebook
---

<style type="text/css">
  body{
  font-size: 13pt;
  text-align: justify
      }
</style>


## Setup

```{r setup}
library(here)
library(readxl)
library(readr)
library(dplyr)
library(PerformanceAnalytics)
library(factoextra)
library(janitor)
```


## Questão 1


### 1.1

```{r}
# define o caminho do arquivo
path_xls <- here::here("data_raw", "fred.xls")

# importa o arquivo
taxas_juros <- readxl::read_xls(path_xls)

# visao geral da estrutura dos dados
dplyr::glimpse(taxas_juros)

# elimine a primeira coluna de series_juros
taxas_juros <- taxas_juros[,-1]
dplyr::glimpse(taxas_juros)
```



### 1.2

```{r}
PerformanceAnalytics::chart.Correlation(taxas_juros)
```


### 1.3

```{r}
pca_juros <- prcomp(taxas_juros, scale = TRUE)
summary(pca_juros)
```

```{r}
factoextra::fviz_screeplot(pca_juros,
  choice = "variance", addlabels = TRUE,
  ylim = c(0, 100)
)
```



### 1.4

```{r}
pca_juros$rotation
```


### 1.5



## Questão 2


### 2.1

```{r}
# define o caminho do arquivo
path_csv <- here::here("data_raw", "HousePrices.csv")

# importa o arquivo
house_prices <- readr::read_csv(path_csv)

# visao geral da estrutura dos dados
dplyr::glimpse(house_prices)
```

```{r}
house_prices <- janitor::clean_names(house_prices)
dplyr::glimpse(house_prices)
```


### 2.2

```{r}
#| out-width: 100%
PerformanceAnalytics::chart.Correlation(house_prices)
```



### 2.3

```{r}
#| eval: false
reg1 = lm(price_in_usd ~ rooms, data = house_prices) 
```


```{r}
reg_mult <- lm(price_in_usd ~ rooms + income + tax_rate + percent_commercial,
   data = house_prices) 
summary(reg_mult)
```

### 2.4



### 2.5



### 2.6



### 2.7

```{r}
confint(reg_mult)
```



### 2.8





